# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image_rc, sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1259, 819)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 1271, 851))
        self.frame.setStyleSheet("background-color : #fff")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(680, 300, 511, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setStyleSheet("border :none;\n"
"border-bottom: 1px solid;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("border :none;\n"
"border-bottom : 1px solid;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setStyleSheet("border :none;\n"
"border-bottom : 1px solid;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setStyleSheet("border :none;\n"
"border-bottom : 1px solid;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(840, 120, 171, 91))
        self.label_3.setStyleSheet("font-size : 20px;\n"
"font-style : italic;\n"
"font-weight :bold;\n"
"background : none;")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(690, 640, 491, 41))
        self.pushButton.setStyleSheet("border-radius : 10px;\n"
"background : rgb(85, 85, 255);\n"
"font-size : 20px;\n"
"font-weight : 200px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 690, 201, 50))
        self.pushButton_2.setStyleSheet("border :none;\n"
"color : rgb(0, 0, 255);\n"
"font-size : 17px;\n"
"background : none;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(840, 690, 171, 51))
        self.label_4.setStyleSheet("font-size : 15px;\n"
"background-color : none;")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, -30, 591, 901))
        self.frame_2.setStyleSheet("background : rgba(85, 170, 255,0.5);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(-30, 450, 641, 411))
        self.label_6.setStyleSheet("image: url(:/img/istockphoto-537241730-612x612.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(-30, 0, 761, 491))
        self.label_7.setStyleSheet("image: url(:/img/Gedung-Kosong.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(870, 50, 101, 91))
        self.label_5.setStyleSheet("image : url(:/img/Computer (1).png)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(790, 210, 534, 36))
        self.label.setStyleSheet("font-size : 30px;\n"
"font-weight : bold;\n"
"background : none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(670, 230, 534, 78))
        self.label_2.setStyleSheet("font-size : 20px;\n"
"background : none;")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(880, 790, 141, 21))
        self.label_8.setStyleSheet("font-size : 13px;")
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Nama Lengkap Sesuai KTP"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Email Pendaftar"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Konfirmasi Password"))
        self.label_3.setText(_translate("Form", "7SENS STATION"))
        self.pushButton.setText(_translate("Form", "Daftar"))
        self.pushButton_2.setText(_translate("Form", "Log in"))
        self.label_4.setText(_translate("Form", "Sudah Punya Akun?"))
        self.label.setText(_translate("Form", "Pendaftaran Akun"))
        self.label_2.setText(_translate("Form", "Silahkan Isi Form berikut untuk mendaftar akun Perusahaan"))
        self.label_8.setText(_translate("Form", "By : Senoaji Putra"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
